// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hotelservices.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_FormatXML extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String XMLToFormat;

	public JA_FormatXML(
		IContext context,
		java.lang.String _xMLToFormat
	)
	{
		super(context);
		this.XMLToFormat = _xMLToFormat;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		XmlFormatter FormatHelper = new XmlFormatter();
        String xmlString = XMLToFormat;
        // Format the XML string
        String formattedXml = FormatHelper.formatXml(xmlString);

        // Print the formatted XML
        return(formattedXml);
    
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_FormatXML";
	}

	// BEGIN EXTRA CODE
	
	// END EXTRA CODE
}
