// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package logging.actions;

import java.util.zip.GZIPOutputStream;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.URLEncoder;
import java.util.Base64;

public class JA_GZipAndBase64String_Encode extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String InputString;

	public JA_GZipAndBase64String_Encode(
		IContext context,
		java.lang.String _inputString
	)
	{
		super(context);
		this.InputString = _inputString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
            // Gzippen van de input string
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            GZIPOutputStream gzipOut = new GZIPOutputStream(baos);
            gzipOut.write(InputString.getBytes("UTF-8"));
            gzipOut.close();
            byte[] gzipBytes = baos.toByteArray();

            // Base64 encoden van de gegzippte bytes
            String output = Base64.getEncoder().encodeToString(gzipBytes);
        	
            return URLEncoder.encode(output, "UTF-8");
            
        } catch (IOException e) {
            e.printStackTrace();
            
            return null;
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GZipAndBase64String_Encode";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
