// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rediscache.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import redisconnector.impl.RedisConnector;

/**
 * Set key to hold the string value. If key already holds a value, it is overwritten, regardless of its type. Any previous time to live associated with the key is discarded on successful SET operation.
 * 
 * Options
 * Starting with Redis 2.6.12 SET supports a set of options that modify its behavior:
 * 
 * EX seconds -- Set the specified expire time, in seconds.
 * PX milliseconds -- Set the specified expire time, in milliseconds.
 * NX -- Only set the key if it does not already exist.
 * XX -- Only set the key if it already exist.
 * Note: Since the SET command options can replace SETNX, SETEX, PSETEX, it is possible that in future versions of Redis these three commands will be deprecated and finally removed.
 * 
 * Return value
 * Simple string reply: OK if SET was executed correctly. Null reply: a Null Bulk Reply is returned if the SET operation was not performed because the user specified the NX or XX option but the condition was not met.
 */
public class SetWithExpire extends CustomJavaAction<java.lang.Void>
{
	private final java.lang.String key;
	private final java.lang.String value;
	private final java.lang.Long seconds;

	public SetWithExpire(
		IContext context,
		java.lang.String _key,
		java.lang.String _value,
		java.lang.Long _seconds
	)
	{
		super(context);
		this.key = _key;
		this.value = _value;
		this.seconds = _seconds;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		RedisConnector redisconnector = new RedisConnector(); 
		redisconnector.set(key, value);
		redisconnector.expire(key, seconds.intValue());
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetWithExpire";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
