// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package flydubai.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetMicroflowName extends CustomJavaAction<java.lang.String>
{
	public GetMicroflowName(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		int size = getContext().getActionStack().size();
		while (size-- >= 0) {
			Object obj = getContext().getActionStack().get(size);
			if (obj.getClass().getName().contains("MicroflowImpl"))
				return getContext().getActionStack().get(size).getActionName();
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetMicroflowName";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
