// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hotelservices.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_CapitalizeWords extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String Input;

	public JA_CapitalizeWords(
		IContext context,
		java.lang.String _input
	)
	{
		super(context);
		this.Input = _input;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return capitalizeWords(Input);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_CapitalizeWords";
	}

	// BEGIN EXTRA CODE
    public static String capitalizeWords(String input) {
        String[] words = input.split("\\s+");
        StringBuilder sb = new StringBuilder();
        
        for (String word : words) {
            if (!word.isEmpty()) {
                // Capitalize first letter of each word
                sb.append(Character.toUpperCase(word.charAt(0)));
                if (word.length() > 1) {
                    // Append the rest of the word in lowercase
                    sb.append(word.substring(1).toLowerCase());
                }
                sb.append(" "); // Add space between words
            }
        }
        
        return sb.toString().trim(); // Remove trailing whitespace and return the capitalized string
    }
	// END EXTRA CODE
}
