// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hotels_roomsxml.actions;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import org.apache.commons.io.IOUtils;
import com.github.junrar.Archive;
import com.github.junrar.rarfile.FileHeader;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import hotels_roomsxml.proxies.RoomsXMLFileHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_File_UnRar extends CustomJavaAction<java.util.List<IMendixObject>>
{
	/** @deprecated use File.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __File;
	private final system.proxies.FileDocument File;

	public JA_File_UnRar(
		IContext context,
		IMendixObject _file
	)
	{
		super(context);
		this.__File = _file;
		this.File = _file == null ? null : system.proxies.FileDocument.initialize(getContext(), _file);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> mendixObjectsList = new ArrayList<IMendixObject>();
		
		try (InputStream inputStream = Core.getFileDocumentContent(this.getContext(), File.getMendixObject())) {
			
			@SuppressWarnings("resource")
			Archive archive = new Archive(inputStream);
			while (true) {
				  FileHeader fileHeader = archive.nextFileHeader();
				  if (fileHeader == null) {
				      break;
				  }
				  try (InputStream is = archive.getInputStream(fileHeader)) {
					  
					  RoomsXMLFileHelper helper = new RoomsXMLFileHelper(this.getContext());
					  helper.setContent(IOUtils.toString(is, StandardCharsets.UTF_8));
					  helper.setFileName(fileHeader.getFileName());
					  mendixObjectsList.add(helper.getMendixObject());
				  }
			}	
		}
		
		return mendixObjectsList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_File_UnRar";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
