// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package qgotheme.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IFeedback.FormTarget;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;

public class JA_GoToPageOrMicroflow extends CustomJavaAction<java.lang.Void>
{
	private final java.lang.Boolean OpenMicroflow;
	private final java.lang.String PageOrMicroflowName;

	public JA_GoToPageOrMicroflow(
		IContext context,
		java.lang.Boolean _openMicroflow,
		java.lang.String _pageOrMicroflowName
	)
	{
		super(context);
		this.OpenMicroflow = _openMicroflow;
		this.PageOrMicroflowName = _pageOrMicroflowName;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (OpenMicroflow) {
			String microflowName = PageOrMicroflowName.replaceAll("/",".");
			com.mendix.core.Core.microflowCall(microflowName).execute(this.getContext());
		} else {
			FeedbackHelper.addOpenFormFeedback(getContext(), PageOrMicroflowName, FormTarget.CONTENT);
		}
		
		return null;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GoToPageOrMicroflow";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
