// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package logging.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.google.gson.*;

public class JA_PrettyPrintJson extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String JsonString;

	public JA_PrettyPrintJson(
		IContext context,
		java.lang.String _jsonString
	)
	{
		super(context);
		this.JsonString = _jsonString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		Gson gson = new GsonBuilder().setPrettyPrinting().create();
		JsonParser jp = new JsonParser();
		JsonElement je = jp.parse(JsonString);
		String prettyJsonString = gson.toJson(je);		
		return prettyJsonString;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_PrettyPrintJson";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
