// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package railways.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import java.util.regex.*;
import java.util.ArrayList;
import com.mendix.webui.CustomJavaAction;

public class JA_TravelDaysNormalizer extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String inputSentence;

	public JA_TravelDaysNormalizer(
		IContext context,
		java.lang.String _inputSentence
	)
	{
		super(context);
		this.inputSentence = _inputSentence;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return TravelDaysNormalizer.normalizeTravelDays(inputSentence);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_TravelDaysNormalizer";
	}

	// BEGIN EXTRA CODE
	public static class TravelDaysNormalizer {

	    public static String normalizeTravelDays(String inputSentence) {
	        if (inputSentence == null || inputSentence.isEmpty()) {
	            return "";
	        }

	        // Regex to match "<number> <time unit>"
	        Pattern pattern = Pattern.compile("\\b(\\d+)\\s+(\\w+)");
	        Matcher matcher = pattern.matcher(inputSentence);

	        ArrayList<String> normalized = new ArrayList<>();
	        while (matcher.find()) {
	            String number = matcher.group(1);
	            String unit = matcher.group(2).toLowerCase();

	            // Normalize units
	            if (unit.contains("day")) {
	                unit = "day";
	            } else if (unit.contains("month")) {
	                unit = "month";
	            }

	            // Add to normalized list
	            normalized.add(number + " " + unit);
	        }

	        // Join the normalized parts into a single string
	        return String.join(", ", normalized);
	    }
	}

	// END EXTRA CODE
}
