// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package logging.actions;

import java.net.URLEncoder;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_UrlEncode extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String InputString;

	public JA_UrlEncode(
		IContext context,
		java.lang.String _inputString
	)
	{
		super(context);
		this.InputString = _inputString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
	    return URLEncoder.encode(InputString, "UTF-8");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_UrlEncode";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
