// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package rediscache.actions;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import rediscache.proxies.RedisKeysHelper;
import redisconnector.impl.RedisConnector;

/**
 * Get the value of key. If the key does not exist the special value nil is returned. An error is returned if the value stored at key is not a string, because GET only handles string values.
 * 
 * Return value
 * Bulk string reply: the value of key, or nil when key does not exist.
 * 
 * 
 */
public class Keys extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private final java.lang.String key;

	public Keys(
		IContext context,
		java.lang.String _key
	)
	{
		super(context);
		this.key = _key;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		RedisConnector redisconnector = new RedisConnector();
		Set<String> stringSet = redisconnector.keys(key);
		
		List<IMendixObject> returnList = new ArrayList<IMendixObject>();
		Integer index = 0;
		for (String key : stringSet) {
			IMendixObject splitPart = Core.instantiate(getContext(), RedisKeysHelper.getType());
			splitPart.setValue(getContext(), RedisKeysHelper.MemberNames.Content.toString(), redisconnector.get(key));
			splitPart.setValue(getContext(), RedisKeysHelper.MemberNames.Key.toString(), key);
			returnList.add(splitPart);
			index = index + 1;
		}
		return returnList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Keys";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
