// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package flight.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class RemoveHTMLTags extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String Content;

	public RemoveHTMLTags(
		IContext context,
		java.lang.String _content
	)
	{
		super(context);
		this.Content = _content;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		 String htmlTagRegex = "<[^>]*>";
        Pattern htmlTagPattern = Pattern.compile(htmlTagRegex);
        Matcher htmlTagMatcher = htmlTagPattern.matcher(Content);
        String withoutHtmlTags = htmlTagMatcher.replaceAll("");

        // Remove extra white spaces
        String withoutSpaces = withoutHtmlTags.replaceAll("\\s+", " ").trim();

        return withoutSpaces;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RemoveHTMLTags";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
